apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-worker
  template:
    metadata:
      labels:
        app: review-worker
    spec:
      containers:
        - name: review-worker
          image: yelp-review-worker:latest
          imagePullPolicy: Never
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: MONGO_URL
              value: "mongodb://mongodb:27017"
            - name: MONGO_DB_NAME
              value: "yelp_lab2"
