apiVersion: v1
kind: Secret
metadata:
  name: yelp-prototype-secrets
  namespace: yelp-prototype
type: Opaque
data:
  DB_USER: cm9vdA==
  DB_PASSWORD: eWVscF9yb290X2Rldg==
  JWT_SECRET: Q0hBTkdFX01FX0pXVF9TRUNSRVQ=
  GEMINI_API_KEY: Q0hBTkdFX01FX0dFTUlOSV9BUElfS0VZ
  TAVILY_API_KEY: Q0hBTkdFX01FX1RBVklMWV9BUElfS0VZ
  YELP_API_KEY: Q0hBTkdFX01FX1lFTFBfQVBJX0tFWQ==
