apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
  namespace: yelp-prototype
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
        - name: restaurant-service
          image: 451978385896.dkr.ecr.us-east-1.amazonaws.com/yelp-prototype/restaurant_service:latest
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: yelp-prototype-config
            - secretRef:
                name: yelp-prototype-secrets
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /
              port: 8002
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8002
            initialDelaySeconds: 30
            periodSeconds: 20
