apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  namespace: yelp-prototype
spec:
  type: ClusterIP
  selector:
    app: restaurant-service
  ports:
    - port: 8002
      targetPort: 8002
